#!/bin/bash

COUNT=1
STEP=10000
N=1
DF=""

echo "Check from cycle :"
read COUNT
echo "To :"
read N
echo "Start Checking ..."
STEP=$(((N-COUNT)/10))
if [ $STEP -le 0 ] ;
then
	STEP=1
fi
while [ $COUNT -le $N ] ;
do
	`./core -dump $COUNT helltrain.cor > aaaa`
	`./corewar -d $COUNT helltrain.cor > bbbb`
	`diff aaaa bbbb > cccc`
	DF=`cat cccc`
	if [ "$DF" != "" ] ;
	then
		if [ $STEP -le 1 ] ;
		then
			echo $COUNT
			echo "$DF"
			exit 0
		else
			if [ $COUNT -le $STEP ] ;
			then
				STEP=0
			fi
			COUNT=$((COUNT-STEP))
			STEP=$((STEP/2))
			COUNT=$((COUNT+STEP))
		fi
	else
		COUNT=$((COUNT+STEP))
	fi
done
